config/routes.rb
Rails.application.routes.draw do

  resources :genres
  resources :comments
  resources :songs do
  resources :likes
  end

  get 'users/show'
  devise_for :users

  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/songs', to: 'static_pages#songs'
  get '/genres', to: 'static_pages#genres'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
    #has_many :song_genres
    #has_many :songs, :through => :song_genres
    has_and_belongs_to_many :songs
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.fetch(:genre).permit(:name, :image)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<div class="sign__content" style="align-items:start">
        				<%= form_with(model: genre, local: true, :class => "sign__form") do |form| %>
                  <% if genre.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>
                
                      <ul>
                        <% genre.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
  
        					<!--<a href="index.html" class="sign__logo">-->
        					<!--	<img src="img/logo.svg" alt="">-->
        					<!--</a>-->
        					<%= link_to root_path, :class => "sign__logo" do %>	
        						<%= image_pack_tag "img/logo.svg" %>
        					<% end %>

                    <div class="field sign__group">
                      <%= form.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Name of genre", :class => "sign__input" %>
                    </div>
               
                            
    						  <div class="actions", style="width:100%">
                                <%= form.submit 'Submit', :style => "transition: 0.4s ease;cursor: pointer;border:none", :class => "sign__btn" %>
                              </div>
							
              <% if action_name == "edit" %>
							  <span class="sign__text"> New genre ? <%= link_to 'New genre', new_genre_path %></span>
							<% end %>
						<!--</form>-->
						<% end %>
						<!-- registration form -->

</div>

app/views/genres/edit.html.erb
<div class="sign section--bg" data-bg="img/section/section.jpg" style="padding-top:90px">
		<div class="container">
			<div class="row">
				<div class="col-12">
			
                        <h1 style="color:white">Editing genre</h1>

                            <%= render 'form', genre: @genre %>

            </div>
        </div>
	</div>
</div>

app/views/genres/index.html.erb
	<section class="section section--first section--bg" data-bg="img/section/section.jpg">
		<p id="notice" style="color:white"><%= notice %></p>
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section__wrap">
						<!-- section title -->
						<h2 class="section__title">Genres list
							<% if admin %>
								| 
								<%= link_to 'New Genre', new_genre_path %>
							<!-- end content title -->
							<% end %>
					
						</h2>
						<!-- end section title -->

						<!-- breadcrumb -->
						<ul class="breadcrumb">
							<li class="breadcrumb__item"><a href="#">Home</a></li>
							<li class="breadcrumb__item breadcrumb__item--active">Songs list</li>
						</ul>
						<!-- end breadcrumb -->
					</div>
				</div>
			</div>
		</div>
	</section>
	
	<!-- catalog -->
	<div class="catalog" style="margin-top:50px">
		<div class="container">
			<div class="row">
				<!-- card -->
				<% @genres.each do |genre| %>
				    
					<div class="col-6 col-sm-4 col-lg-3 col-xl-2">
						<div class="card">
							<%= link_to genre, :class => "genre_link" do %>
								<div>
									<%= genre.name %>
								</div>
                                 
                            <% end %>
						</div>
					</div>
					<% if admin %>
						<%= link_to 'Edit', edit_genre_path(genre) %>,  
						<%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %>
					<!-- end content title -->
					<% end %>
					
					<!-- end card -->
				<% end %>

			</div>
		</div>
	</div>

app/views/genres/new.html.erb
<div class="sign section--bg" data-bg="img/section/section.jpg" style="padding-top:90px">
		<div class="container">
			<div class="row">
				<div class="col-12">
			
                        <h1 style="color:white">New genre</h1>

                    <%= render 'form', genre: @genre %>

                </div>
            </div>
		</div>
	</div>
</section>

app/views/genres/show.html.erb
<section class="section section--first section--bg" data-bg="img/section/section.jpg">
		<p id="notice" style="color:white"><%= notice %></p>
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section__wrap">
						<!-- section title -->
						<h2 class="section__title"><%= @genre.name %> 
						<% if admin %>
							| <%= link_to 'Edit', edit_genre_path(@genre) %> 
						<!-- end content title -->
						<% end %>
						
						</h2>
						
						<!-- end section title -->

						<!-- breadcrumb -->
						<ul class="breadcrumb">
							<li class="breadcrumb__item"><a href="#">Home</a></li>
							<li class="breadcrumb__item">Genre</li>
							<li class="breadcrumb__item breadcrumb__item--active"><%= @genre.name %></li>
						</ul>
						<!-- end breadcrumb -->
					</div>
				</div>
			</div>
		</div>
	</section>
	
		<div class="catalog" style="margin-top:50px">
		<div class="container">
			<div class="row">
				<!-- card -->
				<% @genre.songs.each do |song| %>
				    
					<div class="col-6 col-sm-4 col-lg-3 col-xl-2">
						<div class="card">
							<div class="card__cover">
								<!--<img src="img/covers/cover.jpg" alt="">-->
								<% if song.image.attached? %>
                                   <%= image_tag song.image  %>
                                 <% end %>
                                 <%= link_to song, :class => "card__play" do %>
                                 	<i class="icon ion-ios-play"></i>
                                 <% end %>
								<!--<a href="#" class="card__play">-->
									
								<!--</a>-->
							</div>
							<div class="card__content">
								<h3 class="card__title"><a href="#"><%= song.title %></a></h3>
								<span class="card__category">
									<% song.genres.each do |genre| %>
										<a href="/genres/<%= genre.id %>"><%= genre.name %></a>
									<% end %>
								</span>
							</div>
						</div>
					</div>
					<!-- end card -->
				<% end %>

			</div>
		</div>
	</div>