config/routes.rb
Rails.application.routes.draw do

  resources :genres
  resources :comments
  resources :songs do
  resources :likes
  end

  get 'users/show'
  devise_for :users

  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/songs', to: 'static_pages#songs'
  get '/genres', to: 'static_pages#genres'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id;

    respond_to do |format|
      if @comment.save
        url = "/songs/" + @comment.song_id.to_s
        format.html { redirect_to url}
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        url = "/songs/" + @comment.song_id.to_s
        format.html { redirect_to url }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      url = "/songs/" + @comment.song_id.to_s
      format.html { redirect_to url }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:user_id, :song_id, :comment)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="sign__content" style="align-items:start">
  <%= form_with(model: comment, local: true, :class => "sign__form") do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
  
        <ul>
          <% comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <%= link_to root_path, :class => "sign__logo" do %>	
        						<%= image_pack_tag "img/logo.svg" %>
        					<% end %>
  
    <p>
      <strong>User:</strong>
      <%= @comment.user.email %>
    </p>
    
    <p>
      <strong>Song:</strong>
      <%= @comment.song_id %>
    </p>
  
    <div class="field">
      <%= form.label :comment %>
      <%= form.text_area :comment, autofocus: true, autocomplete: "comment", placeholder: "Comment", :class => "sign__input" %>
    </div>
  
  <div class="actions", style="width:100%">
      <%= form.submit 'Submit', :style => "transition: 0.4s ease;cursor: pointer;border:none", :class => "sign__btn" %>
    </div>
  <% end %>
</div>

app/views/comments/destroy.js.erb
$('.delete_comment').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/comments/edit.html.erb
<div class="sign section--bg" data-bg="img/section/section.jpg" style="padding-top:90px">
		<div class="container">
			<div class="row">
				<div class="col-12">
                    <h1 style="color:white">Editing Comment</h1>
                    
                    <%= render 'form', comment: @comment %>
                    
                    <% url = "/songs/" + @comment.song_id.to_s %>
            </div>
        </div>
	</div>
</div>

app/views/comments/index.html.erb
<section class="section" style="background:white;margin-top:50px">  
  <p id="notice"><%= notice %></p>
  
  <h1>Comments</h1>
  
  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Song</th>
        <th>Comment</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.user_id %></td>
          <td><%= comment.song_id %></td>
          <td><%= comment.comment %></td>
          <td><%= link_to 'Show', comment %></td>
          <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
          <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, 
          :remote => true, :class => 'delete_comment'%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Comment', new_comment_path %>
  <%= link_to 'Back', songs_path%>
</section>

app/views/comments/new.html.erb
<section class="section" style="background:white;margin-top:50px">    
    <h1>New Comment</h1>
    
    <%= render 'form', comment: @comment %>
    
    <%= link_to 'Back', comments_path %>
</section>

app/views/comments/show.html.erb
<section class="section" style="background:white;margin-top:50px">
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>User:</strong>
    <%= @comment.user.email %>
  </p>
  
  <p>
    <strong>Song:</strong>
    <%= @comment.song_id %>
  </p>
  
  <p>
    <strong>Comment:</strong>
    <%= @comment.comment %>
  </p>
  
  <%= link_to 'Edit', edit_comment_path(@comment) %> |
  <%= link_to 'Back', comments_path %>
</section