config/routes.rb
Rails.application.routes.draw do

  resources :genres
  resources :comments
  resources :songs do
  resources :likes
  end

  get 'users/show'
  devise_for :users

  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/songs', to: 'static_pages#songs'
  get '/genres', to: 'static_pages#genres'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/song.rb
class Song < ApplicationRecord
    has_one_attached :image
    has_one_attached :source
    
    has_many :comment, -> { order "created_at DESC"}

    #has_many :song_genres
    #has_many :genres, :through => :song_genres
    has_and_belongs_to_many :genres
    belongs_to :user
    has_many :likes, dependent: :destroy
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @comment = Comment.new
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    @song.user_id = current_user.id;

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :artist, :image, :source, :user_id, genre_ids:[])
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<div class="sign__content">
        				<%= form_with(model: song, local: true, :class => "sign__form") do |f| %>
        				 <% if song.errors.any? %>
          				  <div class="err-father">
            					<div id="error_explanation">
                        <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>
                  
                        <ul>
                          <% song.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                        </ul>
                      </div>
            				</div>
          				<% end %>
        					<!--<a href="index.html" class="sign__logo">-->
        					<!--	<img src="img/logo.svg" alt="">-->
        					<!--</a>-->
        					<%= link_to root_path, :class => "sign__logo" do %>	
        						<%= image_pack_tag "img/logo.svg" %>
        					<% end %>
							
                  
                    <div class="field sign__group">
                      <%= f.text_field :title, autofocus: true, autocomplete: "title", placeholder: "Title", :class => "sign__input" %>
                    </div>
                    
                    <div class="field sign__group">
                      <%= f.text_field :artist, autofocus: true, autocomplete: "artist", placeholder: "Artist", :class => "sign__input" %>
                    </div>
                    
                    
                    <div class="field sign__group" style="color:white;width:100%">
                      <%= f.label :genre_ids, "Genres" %>
                      <div class="checkbox-form">
                        <div class="checkbox-area">
                          <div class="checkbox-grid">
                          <% Genre.all.each do |genre| %>
                           
                                <div class="row-calendar-check">
                                    <!--<h6><%= genre.name %></h6>-->
                                    <ul>
                                      <li>
                                          <%= check_box_tag "song[genre_ids][]",genre.id,@song.genre_ids.include?(genre.id), { id: "song_genre_ids_#{genre.id}" } %>
                                          <%= label_tag "song[genre_ids][#{genre.id}]",genre.name %>
                                      </li>
                                    </ul>
                              </div>
                          <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                    
                    <label for="song_image" class="custom-file-upload sign__btn">
                        <i class="fa fa-cloud-upload"></i> Image
                    </label>
                    <%= f.file_field :image, :id => "song_image"%><br>
                    
                    <label for="song_source" class="custom-file-upload sign__btn">
                        <i class="fa fa-cloud-upload"></i> Song file
                    </label>
                    <%= f.file_field :source, :id => "song_source"%><br>
                            
                              
    							<!--<div class="sign__group">-->
    							<!--	<input type="text" class="sign__input" placeholder="Name">-->
    							<!--</div>-->
    
    							
    						  <div class="actions", style="width:100%">
                                <%= f.submit 'Submit song', :style => "transition: 0.4s ease;cursor: pointer;border:none", :class => "sign__btn" %>
                              </div>
							
              <% if action_name == "edit" %>
							  <span class="sign__text"> New song ? <%= link_to 'New song', new_song_path %></span>
							<% end %>
						<!--</form>-->
						<% end %>
						<!-- registration form -->

</div>

app/views/songs/edit.html.erb
<div class="sign section--bg" data-bg="img/section/section.jpg" style="padding-top:90px">
		<div class="container">
			<div class="row">
				<div class="col-12">
			
                        <h1 style="color:white">Editing Song</h1>
                        
                        <%= render 'form', song: @song %>
                        

      
                </div>
            </div>
		</div>
	</div>
</section>

app/views/songs/index.html.erb
<!-- page title -->
	<section class="section section--first section--bg" data-bg="img/section/section.jpg">
		<!--<p id="notice" style="color:white"><%= notice %></p>-->
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section__wrap">
						<!-- section title -->
						<h2 class="section__title">Songs list 
						| <%= link_to 'New song', new_song_path %>
						</h2>
						<!-- end section title -->

						<!-- breadcrumb -->
						<ul class="breadcrumb">
							<li class="breadcrumb__item"><a href="#">Home</a></li>
							<li class="breadcrumb__item breadcrumb__item--active">Songs list</li>
						</ul>
						<!-- end breadcrumb -->
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end page title -->

	<!-- filter -->
	<!--<div class="filter">-->
	<!--	<div class="container">-->
	<!--		<div class="row">-->
	<!--			<div class="col-12">-->
	<!--				<div class="filter__content">-->
						<!--<div class="filter__items">-->
							<!-- filter item -->
							<!--<div class="filter__item" id="filter__genre">-->
							<!--	<span class="filter__item-label">GENRE:</span>-->

							<!--	<div class="filter__item-btn dropdown-toggle" role="navigation" id="filter-genre" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
							<!--		<input type="button" value="Action/Adventure">-->
							<!--		<span></span>-->
							<!--	</div>-->

							<!--	<ul class="filter__item-menu dropdown-menu scrollbar-dropdown" aria-labelledby="filter-genre">-->
							<!--		<li>Action/Adventure</li>-->
							<!--		<li>Animals</li>-->
							<!--		<li>Animation</li>-->
							<!--		<li>Biography</li>-->
							<!--		<li>Comedy</li>-->
							<!--		<li>Cooking</li>-->
							<!--		<li>Dance</li>-->
							<!--		<li>Documentary</li>-->
							<!--		<li>Drama</li>-->
							<!--		<li>Education</li>-->
							<!--		<li>Entertainment</li>-->
							<!--		<li>Family</li>-->
							<!--		<li>Fantasy</li>-->
							<!--		<li>History</li>-->
							<!--		<li>Horror</li>-->
							<!--		<li>Independent</li>-->
							<!--		<li>International</li>-->
							<!--		<li>Kids</li>-->
							<!--		<li>Kids & Family</li>-->
							<!--		<li>Medical</li>-->
							<!--		<li>Military/War</li>-->
							<!--		<li>Music</li>-->
							<!--		<li>Musical</li>-->
							<!--		<li>Mystery/Crime</li>-->
							<!--		<li>Nature</li>-->
							<!--		<li>Paranormal</li>-->
							<!--		<li>Politics</li>-->
							<!--		<li>Racing</li>-->
							<!--		<li>Romance</li>-->
							<!--		<li>Sci-Fi/Horror</li>-->
							<!--		<li>Science</li>-->
							<!--		<li>Science Fiction</li>-->
							<!--		<li>Science/Nature</li>-->
							<!--		<li>Spanish</li>-->
							<!--		<li>Travel</li>-->
							<!--		<li>Western</li>-->
							<!--	</ul>-->
							<!--</div>-->
							<!-- end filter item -->

							<!-- filter item -->
							<!--<div class="filter__item" id="filter__quality">-->
							<!--	<span class="filter__item-label">QUALITY:</span>-->

							<!--	<div class="filter__item-btn dropdown-toggle" role="navigation" id="filter-quality" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
							<!--		<input type="button" value="HD 1080">-->
							<!--		<span></span>-->
							<!--	</div>-->

							<!--	<ul class="filter__item-menu dropdown-menu scrollbar-dropdown" aria-labelledby="filter-quality">-->
							<!--		<li>HD 1080</li>-->
							<!--		<li>HD 720</li>-->
							<!--		<li>DVD</li>-->
							<!--		<li>TS</li>-->
							<!--	</ul>-->
							<!--</div>-->
							<!-- end filter item -->

							<!-- filter item -->
							<!--<div class="filter__item" id="filter__rate">-->
							<!--	<span class="filter__item-label">IMBd:</span>-->

							<!--	<div class="filter__item-btn dropdown-toggle" role="button" id="filter-rate" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
							<!--		<div class="filter__range">-->
							<!--			<div id="filter__imbd-start"></div>-->
							<!--			<div id="filter__imbd-end"></div>-->
							<!--		</div>-->
							<!--		<span></span>-->
							<!--	</div>-->

							<!--	<div class="filter__item-menu filter__item-menu--range dropdown-menu" aria-labelledby="filter-rate">-->
							<!--		<div id="filter__imbd"></div>-->
							<!--	</div>-->
							<!--</div>-->
							<!-- end filter item -->

							<!-- filter item -->
							<!--<div class="filter__item" id="filter__year">-->
							<!--	<span class="filter__item-label">RELEASE YEAR:</span>-->

							<!--	<div class="filter__item-btn dropdown-toggle" role="button" id="filter-year" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
							<!--		<div class="filter__range">-->
							<!--			<div id="filter__years-start"></div>-->
							<!--			<div id="filter__years-end"></div>-->
							<!--		</div>-->
							<!--		<span></span>-->
							<!--	</div>-->

							<!--	<div class="filter__item-menu filter__item-menu--range dropdown-menu" aria-labelledby="filter-year">-->
							<!--		<div id="filter__years"></div>-->
							<!--	</div>-->
							<!--</div>-->
							<!-- end filter item -->
						<!--</div>-->
						
						<!-- filter btn -->
	<!--					<button class="filter__btn" type="button">apply filter</button>-->
						<!-- end filter btn -->
	<!--				</div>-->
	<!--			</div>-->
	<!--		</div>-->
	<!--	</div>-->
	<!--</div>-->
	<!-- end filter -->

	<!-- catalog -->
	<div class="catalog" style="margin-top:50px">
		<div class="container">
			<div class="row">
				<!-- card -->
				<% @songs.each do |song| %>
				    
					<div class="col-6 col-sm-4 col-lg-3 col-xl-2">
						<div class="card">
							<div class="card__cover">
								<!--<img src="img/covers/cover.jpg" alt="">-->
								<% if song.image.attached? %>
                                   <%= image_tag song.image  %>
                                 <% end %>
                                 <%= link_to song, :class => "card__play" do %>
                                 	<i class="icon ion-ios-play"></i>
                                 <% end %>
								<!--<a href="#" class="card__play">-->
									
								<!--</a>-->
							</div>
							<div class="card__content">
								<h3 class="card__title"><a href="#"><%= song.title %></a></h3>
								<span class="card__category">
									
									<% song.genres.each do |genre| %>
										<a href="/genres/<%= genre.id %>"><%= genre.name %></a>
									<% end %>
								</span>
								<!--<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>-->
							</div>
						</div>
					</div>
					<!-- end card -->
				<% end %>

			

				<!-- paginator -->
				<!--<div class="col-12">-->
				<!--	<ul class="paginator">-->
				<!--		<li class="paginator__item paginator__item--prev">-->
				<!--			<a href="#"><i class="icon ion-ios-arrow-back"></i></a>-->
				<!--		</li>-->
				<!--		<li class="paginator__item"><a href="#">1</a></li>-->
				<!--		<li class="paginator__item paginator__item--active"><a href="#">2</a></li>-->
				<!--		<li class="paginator__item"><a href="#">3</a></li>-->
				<!--		<li class="paginator__item"><a href="#">4</a></li>-->
				<!--		<li class="paginator__item paginator__item--next">-->
				<!--			<a href="#"><i class="icon ion-ios-arrow-forward"></i></a>-->
				<!--		</li>-->
				<!--	</ul>-->
				<!--</div>-->
				<!-- end paginator -->
			</div>
		</div>
	</div>
	<!-- end catalog -->

app/views/songs/new.html.erb
<div class="sign section--bg" data-bg="img/section/section.jpg" style="padding-top:90px">
		<div class="container">
			<div class="row">
				<div class="col-12">
					
                        <h1 style="color:white">New Song</h1>
                        
                        <%= render 'form', song: @song %>
                        

                </div>
            </div>
		</div>
	</div>
</div>

app/views/songs/show.html.erb
<!-- details -->
	<section class="section details">
		<!-- details background -->
		<div class="details__bg" ></div>
		<!-- end details background -->

		<!-- details content -->
		<div class="container">
			<div class="row">
				<!-- title -->
				<div class="col-12">
					<h1 class="details__title"><%= @song.title %></h1>
				</div>
				<!-- end title -->

				<!-- content -->
				<div class="col-12 col-xl-6">
					<div class="card card--details">
						<div class="row">
							<!-- card cover -->
							<div class="col-12 col-sm-4 col-md-4 col-lg-3 col-xl-5">
								<div class="card__cover">
								    <% if @song.image.attached? %>
                                       <%= image_tag @song.image  %>
                                     <% end %>
									<!--<img src="img/covers/cover.jpg" alt="">-->
								</div>
							</div>
							<!-- end card cover -->

							<!-- card content -->
							<div class="col-12 col-sm-8 col-md-8 col-lg-9 col-xl-7">
								<div class="card__content">
									<!--<div class="card__wrap">-->
									<!--	<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>-->

									<!--	<ul class="card__list">-->
									<!--		<li>HD</li>-->
									<!--		<li>16+</li>-->
									<!--	</ul>-->
									<!--</div>-->

									<ul class="card__meta">
										<li><span>Genre:</span> 
											<% @song.genres.each do |genre| %>
												<a href="/genres/<%= genre.id %>"><%= genre.name %></a>
											<% end %>
										</li>
										<li><span>Artist:</span> <%= @song.artist %></li>
										<li>
											<% if current_user %>
							                     <% if @song.user.email == current_user.email %>
							                         <%= link_to 'Edit', edit_song_path(@song) %> 
							                         <%= link_to 'Delete', @song, method: :delete, data: { confirm: 'Are you sure?' } %>
							
							                     <% end %>
							                 <% end %>   
										</li>
										<!--<li><span>Running time:</span> 120 min</li>-->
										<!--<li><span>Country:</span> <a href="#">USA</a> </li>-->
									</ul>

									<div class="card__description card__description--details">
										<!--It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.-->
									</div>
								</div>
							</div>
							<!-- end card content -->
						</div>
					</div>
				</div>
				<!-- end content -->

				<!-- player -->
				<div class="col-12 col-xl-6">
					<% if @song.source.attached? %>
                     <%= audio_tag( rails_blob_url(@song.source), controls: true) %>
                 <% end %>
				</div>
				<!-- end player -->

				
			</div>
		</div>
		<!-- end details content -->
	</section>
	<!-- end details -->

	<!-- content -->
	<section class="content">
		<div class="content__head">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<!-- content title -->
						<h2 class="content__title">Otokumo</h2>
						<!-- end content title -->

						<!-- content tabs nav -->
						<ul class="nav nav-tabs content__tabs" id="content__tabs" role="tablist">
							<li class="nav-item">
								<a class="nav-link active" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">Comments</a>
							</li>

							<!--<li class="nav-item">-->
							<!--	<a class="nav-link" data-toggle="tab" href="#tab-2" role="tab" aria-controls="tab-2" aria-selected="false">Reviews</a>-->
							<!--</li>-->

							<!--<li class="nav-item">-->
							<!--	<a class="nav-link" data-toggle="tab" href="#tab-3" role="tab" aria-controls="tab-3" aria-selected="false">Photos</a>-->
							<!--</li>-->
						</ul>
						<!-- end content tabs nav -->

						<!-- content mobile tabs nav -->
						<div class="content__mobile-tabs" id="content__mobile-tabs">
							<div class="content__mobile-tabs-btn dropdown-toggle" role="navigation" id="mobile-tabs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<input type="button" value="Comments">
								<span></span>
							</div>

							<div class="content__mobile-tabs-menu dropdown-menu" aria-labelledby="mobile-tabs">
								<ul class="nav nav-tabs" role="tablist">
									<li class="nav-item"><a class="nav-link active" id="1-tab" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">Comments</a></li>

									<li class="nav-item"><a class="nav-link" id="2-tab" data-toggle="tab" href="#tab-2" role="tab" aria-controls="tab-2" aria-selected="false">Reviews</a></li>

									<li class="nav-item"><a class="nav-link" id="3-tab" data-toggle="tab" href="#tab-3" role="tab" aria-controls="tab-3" aria-selected="false">Photos</a></li>
								</ul>
							</div>
						</div>
						<!-- end content mobile tabs nav -->
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="col-12 col-lg-8 col-xl-8">
					<!-- content tabs -->
					<div class="tab-content" id="myTabContent">
						<div class="tab-pane fade show active" id="tab-1" role="tabpanel" aria-labelledby="1-tab">
							<div class="row">
								<!-- comments -->
								<div class="col-12">
									<div class="comments">
										<ul class="comments__list">
											
								             	<% @song.comment.each do |comment|%>
													<li class="comments__item">
														<div class="comments__autor">
															<!--<img class="comments__avatar" src="img/user.png" alt="">-->
															<% if comment.user.avatar.attached? %>
												                <%= image_tag comment.user.avatar, :class => "comments__avatar" %>
												              <% end %>
															
															<span class="comments__name"><%= comment.user.email if comment.user %></span>
															<span class="comments__time"><%= comment.created_at %></span>
														</div>
														<p class="comments__text"><%= comment.comment %></p>
														<div class="comments__actions">
															<!--<div class="comments__rate">-->
															<!--	<button type="button"><i class="icon ion-md-thumbs-up"></i>12</button>-->
		
															<!--	<button type="button">7<i class="icon ion-md-thumbs-down"></i></button>-->
															<!--</div>-->
															<% if current_user %>
																<% if comment.user.email == current_user.email %>
																	<button type="button"><i class="icon ion-ios-share-alt"></i><%= link_to 'Edit', edit_comment_path(comment) %> </button>
																	<button type="button"><i class="icon ion-ios-quote"></i><%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %></button>
											                  
											                     <% end %>
										                     <% end %>
		
															
														</div>
													</li>
												<% end %>
											
										</ul>

										<!--<form action="#" class="form">-->
										<% if current_user %>
						                 	<%= form_with(model: @comment, local: true, :class => "form") do |form| %>
							                <!--<div class= "field">-->
							                  <%= form.text_area :comment, :class => "form__textarea", :placeholder => "Add comment" %>
							                  <%= form.hidden_field :song_id, :value => @song.id %>
							                <!--</div>-->
							                <!--<div class="actions">-->
							                  <%= form.submit 'Send',:style => "transition: 0.4s ease;cursor: pointer;border:none", :class => "form__btn" %>
							                <!--</div>-->
							              <% end %>
							            <% end %> 
										
											<!--<textarea id="text" name="text" class="form__textarea" placeholder="Add comment"></textarea>-->
											<!--<button type="button" class="form__btn">Send</button>-->
										<!--</form>-->
									</div>
								</div>
								<!-- end comments -->
							</div>
						</div>

					</div>
					 <!--end content tabs -->
				</div>

			</div>
		</div>
	</section>
	<!-- end content -->
	
		<!-- Root element of PhotoSwipe. Must have class pswp. -->