config/routes.rb
Rails.application.routes.draw do

  resources :genres
  resources :comments
  resources :songs do
  resources :likes
  end

  get 'users/show'
  devise_for :users

  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/songs', to: 'static_pages#songs'
  get '/genres', to: 'static_pages#genres'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!-- footer -->
	<footer class="footer">
		<div class="container">
			<div class="row">
				<!-- footer list -->
				<div class="col-12 col-md-3">
					<h6 class="footer__title">Download Our App</h6>
					<ul class="footer__app">

					</ul>
				</div>
				<!-- end footer list -->

				<!-- footer list -->
				<div class="col-6 col-sm-4 col-md-3">
					<h6 class="footer__title">Resources</h6>
					<ul class="footer__list">
						<li><a href="#">About Us</a></li>
						<li><a href="#">Pricing Plan</a></li>
						<li><a href="#">Help</a></li>
					</ul>
				</div>
				<!-- end footer list -->

				<!-- footer list -->
				<div class="col-6 col-sm-4 col-md-3">
					<h6 class="footer__title">Legal</h6>
					<ul class="footer__list">
						<li><a href="#">Terms of Use</a></li>
						<li><a href="#">Privacy Policy</a></li>
						<li><a href="#">Security</a></li>
					</ul>
				</div>
				<!-- end footer list -->

				<!-- footer list -->
				<div class="col-12 col-sm-4 col-md-3">
					<h6 class="footer__title">Contact</h6>
					<ul class="footer__list">
						<li><a href="tel:+18002345678">+1 (800) 234-5678</a></li>
						<li><a href="mailto:support@moviego.com">support@flixgo.com</a></li>
					</ul>
					<ul class="footer__social">
						<li class="facebook"><a href="#"><i class="icon ion-logo-facebook"></i></a></li>
						<li class="instagram"><a href="#"><i class="icon ion-logo-instagram"></i></a></li>
						<li class="twitter"><a href="#"><i class="icon ion-logo-twitter"></i></a></li>
						<li class="vk"><a href="#"><i class="icon ion-logo-vk"></i></a></li>
					</ul>
				</div>
				<!-- end footer list -->

				<!-- footer copyright -->
				<div class="col-12">
					<div class="footer__copyright">
						<small><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></small>

						<ul>
							<li><a href="#">Terms of Use</a></li>
							<li><a href="#">Privacy Policy</a></li>
						</ul>
					</div>
				</div>
				<!-- end footer copyright -->
			</div>
		</div>
	</footer>

app/views/layouts/_header.html.erb
	<header class="header">
		<div class="header__wrap">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="header__content">
							<!-- header logo -->
							<!--<a href="index.html" class="header__logo">-->
							<%= link_to root_path, :class => "header__logo" do %>	
								<%= image_pack_tag "img/logo.svg" %>
							<% end %>
							<!--</a>-->
							<!-- end header logo -->

							<!-- header nav -->
							<ul class="header__nav">
								<!-- dropdown -->
								<li class="header__nav-item">
									
								</li>
								<!-- end dropdown -->

								<!-- dropdown -->
								<li class="header__nav-item">
									<%= link_to 'Genres', genres_path, :class => "header__nav-link" %>
										
								
								</li>
								<!-- end dropdown -->
								
								<li class="header__nav-item">
									<%= link_to 'Songs', songs_path, :class => "header__nav-link" %>
									<!--<a href="pricing.html" class="header__nav-link">Pricing Plan</a>-->
								</li>
								
								<li class="header__nav-item">
									<%= link_to 'About', about_path, :class => "header__nav-link" %>
									<!--<a href="pricing.html" class="header__nav-link">Pricing Plan</a>-->
								</li>
								<% if not current_user %>
									<li class="header__nav-item">
											<%= link_to 'Sign Up', new_user_registration_path, :class => "header__nav-link" %>
										
										<!--<a href="faq.html" class="header__nav-link">Help</a>-->
									</li>
									
								<% else %>
									<li class="header__nav-item">
											<%= link_to 'Profile', users_show_path, :class => "header__nav-link" %>
										
									</li>
									
									<li class="header__nav-item">
											<%= link_to 'New Song', new_song_path, :class => "header__nav-link" %>
										
									</li>
								<% end %>
								<!-- dropdown -->
								<li class="dropdown header__nav-item">
								
								</li>
								<!-- end dropdown -->
							</ul>
							<!-- end header nav -->

							<!-- header auth -->
							<div class="header__auth">
								<!--<button class="header__search-btn" type="button">-->
								<!--	<i class="icon ion-ios-search"></i>-->
								<!--</button>-->
								<% if current_user %>
									<%= link_to destroy_user_session_path, method: :delete, :class => 'header__sign-in' do %>
										<i class="icon ion-ios-log-in"></i>
										<span>Sign out</span>
									<% end %>
								<% else %>
									<%= link_to new_user_session_path, :class => 'header__sign-in' do %>
										<i class="icon ion-ios-log-in"></i>
										<span>Sign in</span>
									<% end %>
								<% end %>
								
								<!--<a href="users/sign_in" class="header__sign-in">-->
								<!--	<i class="icon ion-ios-log-in"></i>-->
								<!--	<span>sign in</span>-->
								<!--</a>-->
							</div>
							<!-- end header auth -->

							<!-- header menu btn -->
							<button class="header__btn" type="button">
								<span></span>
								<span></span>
								<span></span>
							</button>
							<!-- end header menu btn -->
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- header search -->
		<!--<form action="#" class="header__search">-->
		<!--	<div class="container">-->
		<!--		<div class="row">-->
		<!--			<div class="col-12">-->
		<!--				<div class="header__search-content">-->
		<!--					<input type="text" placeholder="Search for a movie, TV Series that you are looking for">-->

		<!--					<button type="button">search</button>-->
		<!--				</div>-->
		<!--			</div>-->
		<!--		</div>-->
		<!--	</div>-->
		<!--</form>-->
		<!-- end header search -->
	</header>
	<!-- end header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Otokumo</title>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    

    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
    
  	<!-- Font -->
  	<!--<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600%7CUbuntu:300,400,500,700" rel="stylesheet">-->
  
  	<!-- Favicons -->

  
  	<meta name="description" content="">
  	<meta name="keywords" content="">
  	<meta name="author" content="Dmitry Volkov">
  </head>

  <body>
    
    <%= render 'layouts/header' %>
    <p id="notice" style="color:white"><%= notice %></p>
    <%= yield %>
    <%= render 'layouts/footer' %>



  </body>
</html>